export const places = [
	{
		slug: 'zelengora',
		title: 'Zelengora',
		content: {
            first: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            second: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            third: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.'
        }
	},

	{
		slug: 'vrata',
		title: 'Hajducka Vrata',
		content: {
            first: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            second: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            third: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.'
        }
	},

	{
		slug: 'prenj',
		title: 'Prenj',
		content: {
            first: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            second: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.',

            third: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quam augue, lacinia et dui ac, consequat maximus elit. Fusce id interdum turpis. Quisque vulputate nibh eu imperdiet tristique. Aenean vitae auctor quam, quis porttitor dolor. Aenean metus ex, laoreet eleifend nisi eu, dictum eleifend eros. Aenean imperdiet vestibulum turpis eget tincidunt. Proin diam nulla, molestie id nisl eget, egestas ultricies leo. Cras fringilla odio in porta feugiat. Morbi nisl ipsum, tempor vel ligula ut, facilisis interdum velit. Sed diam dolor, consectetur fringilla leo vel, tempus imperdiet leo. Duis rutrum varius nibh nec sagittis. Nunc pulvinar eget lacus eu aliquet. Vivamus sagittis orci sed viverra maximus. Ut porttitor quis nisi at condimentum. In ac maximus lectus, dignissim laoreet augue. Ut volutpat ante a sollicitudin facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent feugiat vestibulum risus, quis luctus nisl aliquet ut. Nam ultricies lectus non arcu euismod, in luctus ex sodales.'
        }
	}
];
