export const places = [
	{
		slug: 'zelengora',
		title: 'Zelengora',
		content: {
            first: '<p>Hikers grapple with the challenge of anointing one mountain as the most enchanting, yet the consensus is resolute when it comes to Zelengora. It wears the crown of beauty. Its name, both symbolic and true, paints a vivid picture of Zelengora as a tapestry adorned with forests, meadows, and alpine fields strewn with vibrant blossoms. What lends a unique charm to this majestic peak are its "mountain eyes". A collection of glacial lakes nestled gracefully at the very base of its peaks. Nestled within the embrace of the Sutjeska National Park, Zelengora beckons avid hikers along its well-marked trails and pathways leading to four mountain sanctuaries: Bogunovac, Dobre Vode, Donje Bare, and the ethereal Orlovačko Lake, where an overnight sojourn becomes an invitation to luxuriate in the pristine air and the breathtaking embrace of nature</p>',

            second: '<p>Zelengora, an ethereal mountain cradled in the embrace of Bosnia and Herzegovina, stands as a crown jewel within the majestic "Sutjeska" National Park, sharing its magnificence with the Lelija, Maglić, and Volujak mountains. Much more than a mere elevation, Zelengora unfolds its allure as a mountain plateau, its undulating highlands giving rise to majestic ridges that pierce the heavens. </p> <br>   Within this enchanting realm, a plethora of crystalline springs gush forth, offering clear, drinkable, and invigoratingly cold water. Here, amidst the bosom of Zelengora, lie several glacial lakes, affectionately known as "mountain eyes." Among them, the renowned Kotlaničko Lake, Orlovačko Lake, Štirinsko Lake, Jugovo Lake, Donje Bare, Gornje Bare, and more, each a reflective jewel mirroring the skies above.</p> <br>   To the east, a rugged canyon unfolds, carved by the untamed river Hrčavka, adding a touch of wilderness to the landscape. The zenith of Zelengora, crowned by the majestic Bregoč at 2015 meters, presides over a dozen other peaks, each gracefully ascending to around 2000 meters above sea level. These peaks, and the undulating ridges upon which they rest, serve as impeccable vantage points, offering panoramic views that transcend the ordinary. </p>   <br> <p>Zelengora is a sanctuary for diverse flora and fauna, its slopes adorned with verdant pastures and stark barren lands above the dense forest canopy. Within this pristine expanse, no permanent settlements exist on the mountain itself. Once, scattered huts adorned active katuns, where cattle grazed the pastures from late May to mid-September, creating a harmonious interlude with nature\'s rhythms.</p>',

            third: '<p>Many hikers delight in traversing expansive meadows and forests, where the prospect of discovering fresh mushrooms or the sweet treasures of strawberries and raspberries adds to the joy of the journey. Some, on the other hand, relish the challenge of ascending steep, pointed peaks, their beauty multiplied in the shimmering surface of mountain lakes. While a select few dedicate themselves to the art of alpinism, seeking out mountains adorned with grand rocky walls as their chosen domain.</p> <br>   <p>There are few mountains that can harmonize these diverse preferences, and Zelengora is among them. This mountain boasts beautiful lakes, lush forests, green meadows, and cliffs whose precipices serve as favored abodes for graceful chamois.</p> <br>   <p>A portion of Zelengora falls within the confines of the Sutjeska National Park, where stringent regulations contribute to the preservation of nature. It is with satisfaction that we acknowledge Zelengora as a mountain graced with vast forested expanses and a rich tapestry of fauna and flora."</p>'
        }
	},

	{
		slug: 'cvrsnica',
		title: 'Čvrsnica',
		content: {
            first: '<p>In the enchanting tapestry of natural wonders, there emerges a true jewel among Herzegovina\'s peaks – the graceful silhouette of Čvrsnica, a sister to Austria\'s majestic Mt Plassen, adorned with panoramic views that embrace glistening glaciers. A cherished trail meanders through the heart of Čvrsnica, guiding wanderers to the ethereal Hajdučka Vrata, a natural marvel etched into limestone cliffs over centuries, perched on the edge of Diva Grabovica\'s canyon. At an elevation of 2,000 meters, Hajdučka Vrata whispers tales of hajduks and beckons hikers, nature aficionados, and photographers alike. From this lofty vantage point, a priceless tableau unfolds – the meandering beauty of Diva Grabovica, the rugged embrace of Veliki Kuk, the timeless presence of Čabulja, Velež, Prenj, and beyond.</p>',

            second: '<p>As the sun dips below the horizon, the night finds its canvas in the famed mountain refuge of Vilinac, where dreams intertwine with the whispers of the mountain breeze. Come the dawn, a leisurely sojourn unveils the path to Bosnia and Herzegovina\'s highest mountain lake, Crvenjak, where pristine waters mirror the heavens above, inviting reflection and reverence in the heart of nature\'s sanctuary.</p> <br>   <p> The exquisite Hajdučka Vrata, nestled within the heart of Čvrsnica, emerge as a poetic masterpiece sculpted by the tender courtship of winds entwining with cascading rains, a melodic symphony whispered by thunderstorms, and the unveiling of secrets concealed behind the ever-shifting veils of clouds. Embraced by the rare tapestry of vegetation that graces this mountain sanctuary, every contour of these celestial gates tells a tale of timeless beauty.</p>',

            third: '<p>Legend weaves its own spell around this enchanting site, where a five-meter-wide stone circle materialized from the very essence of nothingness. It served as a sacred gathering place for the valiant hajduks who defiantly stood against the Ottomans. Positioned majestically at 2,000 meters above sea level, the legend whispers that those who passed through this celestial portal found themselves cloaked in an ethereal shield, rendering them immune to the bite of bullets.</p> <br>   <p> In the embrace of these mystical gates, on the edge of the Diva Grabovica canyon, dreams once envisioned the cinematic magic of the Lord of the Rings trilogy. Yet, the grandiosity of nature\'s theater and the rugged poetry of the terrain gracefully swayed filmmakers away, leaving this pristine canvas untouched. Amidst this wilderness, however, the resilient spirit of the mountains prevails, witnessed in the artful reconstruction of the mountain refuge Vilinac, a beacon of tranquility echoing through the untamed beauty of Čvrsnica.</p>'
        }
	},

	{
		slug: 'prenj',
		title: 'Prenj',
		content: {
            first: '<p>Devotees of Mount Prenj, with an endearing nod to its grandeur, tenderly calling it Planet, a title that transcends mere affection. Their deep appreciation stems from an unwavering understanding that this resplendent Herzegovinian jewel cradles within its embrace invaluable natural treasures, casting it among the most breathtaking landscapes. The zenith of Prenj, Zelena Glava, majestically rises to 2,115 meters above sea level, flanked by the distinguished companionship of Lupoglav, Otiš, Herač, Velika Kapa, and a host of others.</p> <br> <p>From the celestial heights of these peaks, a panoramic tapestry unfolds, revealing lakes, rivers, mountains, and cities held in an enchanting embrace. Prenj, a formidable realm beckoning seasoned hikers and adrenaline enthusiasts alike, boasts a network of trails, some artfully marked, others with a more discreet guidance, amidst a landscape adorned with a multitude of rocks and walls demanding not just strength but an artful finesse to traverse. Yet, upon conquering Prenj, an indelible connection is forged in the bloodstream, an allure that beckons one back time and again.</p> <br> ',

            second: '<p>The highest peak is called Zelena Glava, standing at 2,103 meters above sea level. Prenj is a part of the Dinaric Alps, comprising the most expansive mountain range in the country. The mountain is often referred to as the "Herzegovinian Himalayas" due to its breathtaking vistas and the unique wildlife it hosts.</p> <br>   <p>This majestic mountain range offers some of the most spectacular views in Europe, along with numerous outdoor activities for visitors to enjoy. Three cities surround the foothills of Mount Prenj: Konjic, Jablanica, and Mostar. Therefore, if you wish to explore local heritage and culture, you can visit everything surrounding Mount Prenj.</p> <br>   <p>The Prenj mountain area provides numerous opportunities for hikers, climbers, skiers, and snowboarders alike to explore its many trails and peaks. For those seeking a more leisurely experience, there are many picturesque spots with breathtaking views that can be enjoyed comfortably from your own vehicle or on foot if you prefer hiking tours!</p> <br>   <p>Mount Prenj is also home to rich wildlife, including various bird species, making it an excellent destination for birdwatching enthusiasts. Set up your tent along the lush green slopes of the mountain and spend the night under the stars.</p>',

            third: '<p>For those yearning to embark on a sojourn into the enchanting realms of this magical mountain, we fervently recommend commencing the journey in the company of an experienced guide or by participating in an orchestrated expedition with the esteemed fellowship of numerous mountaineering societies.</p>   <br> <p>If you are in search of an unforgettable adventure, look no further than Mount Prenj – it promises something special regardless of your interests! Whether participating in thrilling outdoor activities like skiing or climbing, or simply absorbing everything nature has to offer while marveling at some truly incredible landscapes, this destination offers something uniquely memorable that won\'t be quickly forgotten.</p>'
        }
	}
];
